name: gits_extension
description: Superpowers for Dart. Collection of useful static extension methods.
version: 0.0.5
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/flutter-library/tree/main/packages/gits_extension

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  time: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
