name: gits_cucumber
description: A gherkin / cucumber integration test runner flutter with gits_cli.
version: 1.2.0
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/flutter-library/tree/main/packages/gits_cucumber

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter

  collection: ^1.16.0
  equatable: ^2.0.5
  patrol: ^1.0.7

dev_dependencies:
  lints: ^2.0.1
